export const mockWeatherResponse = {
    lat: 48.2085,
    lon: 16.3721,
    timezone: 'Europe/Vienna',
    timezone_offset: 7200,
    current: {
        dt: 1750271442,
        sunrise: 1750215212,
        sunset: 1750273067,
        temp: 24.53,
        feels_like: 24.58,
        pressure: 1020,
        humidity: 59,
        dew_point: 16,
        uvi: 0,
        clouds: 0,
        visibility: 10000,
        wind_speed: 1.03,
        wind_deg: 340,
        weather: [
            {
                id: 800,
                main: 'Clear',
                description: 'clear sky',
                icon: '01d',
            },
        ],
    },
    minutely: [
        {
            dt: 1750271460,
            precipitation: 0,
        },
        {
            dt: 1750271520,
            precipitation: 0,
        },
        {
            dt: 1750271580,
            precipitation: 0,
        },
        {
            dt: 1750271640,
            precipitation: 0,
        },
        {
            dt: 1750271700,
            precipitation: 0,
        },
        {
            dt: 1750271760,
            precipitation: 0,
        },
        {
            dt: 1750271820,
            precipitation: 0,
        },
        {
            dt: 1750271880,
            precipitation: 0,
        },
        {
            dt: 1750271940,
            precipitation: 0,
        },
        {
            dt: 1750272000,
            precipitation: 0,
        },
        {
            dt: 1750272060,
            precipitation: 0,
        },
        {
            dt: 1750272120,
            precipitation: 0,
        },
        {
            dt: 1750272180,
            precipitation: 0,
        },
        {
            dt: 1750272240,
            precipitation: 0,
        },
        {
            dt: 1750272300,
            precipitation: 0,
        },
        {
            dt: 1750272360,
            precipitation: 0,
        },
        {
            dt: 1750272420,
            precipitation: 0,
        },
        {
            dt: 1750272480,
            precipitation: 0,
        },
        {
            dt: 1750272540,
            precipitation: 0,
        },
        {
            dt: 1750272600,
            precipitation: 0,
        },
        {
            dt: 1750272660,
            precipitation: 0,
        },
        {
            dt: 1750272720,
            precipitation: 0,
        },
        {
            dt: 1750272780,
            precipitation: 0,
        },
        {
            dt: 1750272840,
            precipitation: 0,
        },
        {
            dt: 1750272900,
            precipitation: 0,
        },
        {
            dt: 1750272960,
            precipitation: 0,
        },
        {
            dt: 1750273020,
            precipitation: 0,
        },
        {
            dt: 1750273080,
            precipitation: 0,
        },
        {
            dt: 1750273140,
            precipitation: 0,
        },
        {
            dt: 1750273200,
            precipitation: 0,
        },
        {
            dt: 1750273260,
            precipitation: 0,
        },
        {
            dt: 1750273320,
            precipitation: 0,
        },
        {
            dt: 1750273380,
            precipitation: 0,
        },
        {
            dt: 1750273440,
            precipitation: 0,
        },
        {
            dt: 1750273500,
            precipitation: 0,
        },
        {
            dt: 1750273560,
            precipitation: 0,
        },
        {
            dt: 1750273620,
            precipitation: 0,
        },
        {
            dt: 1750273680,
            precipitation: 0,
        },
        {
            dt: 1750273740,
            precipitation: 0,
        },
        {
            dt: 1750273800,
            precipitation: 0,
        },
        {
            dt: 1750273860,
            precipitation: 0,
        },
        {
            dt: 1750273920,
            precipitation: 0,
        },
        {
            dt: 1750273980,
            precipitation: 0,
        },
        {
            dt: 1750274040,
            precipitation: 0,
        },
        {
            dt: 1750274100,
            precipitation: 0,
        },
        {
            dt: 1750274160,
            precipitation: 0,
        },
        {
            dt: 1750274220,
            precipitation: 0,
        },
        {
            dt: 1750274280,
            precipitation: 0,
        },
        {
            dt: 1750274340,
            precipitation: 0,
        },
        {
            dt: 1750274400,
            precipitation: 0,
        },
        {
            dt: 1750274460,
            precipitation: 0,
        },
        {
            dt: 1750274520,
            precipitation: 0,
        },
        {
            dt: 1750274580,
            precipitation: 0,
        },
        {
            dt: 1750274640,
            precipitation: 0,
        },
        {
            dt: 1750274700,
            precipitation: 0,
        },
        {
            dt: 1750274760,
            precipitation: 0,
        },
        {
            dt: 1750274820,
            precipitation: 0,
        },
        {
            dt: 1750274880,
            precipitation: 0,
        },
        {
            dt: 1750274940,
            precipitation: 0,
        },
        {
            dt: 1750275000,
            precipitation: 0,
        },
    ],
    hourly: [
        {
            dt: 1750269600,
            temp: 24.82,
            feels_like: 24.85,
            pressure: 1020,
            humidity: 57,
            dew_point: 15.73,
            uvi: 0.17,
            clouds: 15,
            visibility: 10000,
            wind_speed: 1.05,
            wind_deg: 352,
            wind_gust: 1.34,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750273200,
            temp: 24.53,
            feels_like: 24.58,
            pressure: 1020,
            humidity: 59,
            dew_point: 16,
            uvi: 0,
            clouds: 0,
            visibility: 10000,
            wind_speed: 0.85,
            wind_deg: 300,
            wind_gust: 0.86,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750276800,
            temp: 24.36,
            feels_like: 24.37,
            pressure: 1020,
            humidity: 58,
            dew_point: 15.57,
            uvi: 0,
            clouds: 10,
            visibility: 10000,
            wind_speed: 1.29,
            wind_deg: 279,
            wind_gust: 1.25,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750280400,
            temp: 23.74,
            feels_like: 23.74,
            pressure: 1020,
            humidity: 60,
            dew_point: 15.52,
            uvi: 0,
            clouds: 27,
            visibility: 10000,
            wind_speed: 1.57,
            wind_deg: 277,
            wind_gust: 1.49,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750284000,
            temp: 22.66,
            feels_like: 22.57,
            pressure: 1021,
            humidity: 61,
            dew_point: 14.76,
            uvi: 0,
            clouds: 44,
            visibility: 10000,
            wind_speed: 1.6,
            wind_deg: 278,
            wind_gust: 1.54,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750287600,
            temp: 21.33,
            feels_like: 21.16,
            pressure: 1021,
            humidity: 63,
            dew_point: 14.01,
            uvi: 0,
            clouds: 52,
            visibility: 10000,
            wind_speed: 1.46,
            wind_deg: 285,
            wind_gust: 1.45,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750291200,
            temp: 19.77,
            feels_like: 19.63,
            pressure: 1021,
            humidity: 70,
            dew_point: 13.9,
            uvi: 0,
            clouds: 57,
            visibility: 10000,
            wind_speed: 1.57,
            wind_deg: 306,
            wind_gust: 1.41,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750294800,
            temp: 18.96,
            feels_like: 18.77,
            pressure: 1021,
            humidity: 71,
            dew_point: 13.73,
            uvi: 0,
            clouds: 15,
            visibility: 10000,
            wind_speed: 1.67,
            wind_deg: 297,
            wind_gust: 2.02,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750298400,
            temp: 18.48,
            feels_like: 18.24,
            pressure: 1020,
            humidity: 71,
            dew_point: 13.12,
            uvi: 0,
            clouds: 20,
            visibility: 10000,
            wind_speed: 1.83,
            wind_deg: 291,
            wind_gust: 2.7,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750302000,
            temp: 17.99,
            feels_like: 17.72,
            pressure: 1021,
            humidity: 72,
            dew_point: 12.6,
            uvi: 0,
            clouds: 22,
            visibility: 10000,
            wind_speed: 1.92,
            wind_deg: 287,
            wind_gust: 4.93,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750305600,
            temp: 18.25,
            feels_like: 17.96,
            pressure: 1021,
            humidity: 70,
            dew_point: 12.65,
            uvi: 0.2,
            clouds: 21,
            visibility: 10000,
            wind_speed: 1.99,
            wind_deg: 291,
            wind_gust: 6.73,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750309200,
            temp: 20.62,
            feels_like: 20.43,
            pressure: 1021,
            humidity: 65,
            dew_point: 12.94,
            uvi: 0.68,
            clouds: 20,
            visibility: 10000,
            wind_speed: 2.5,
            wind_deg: 297,
            wind_gust: 6.62,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750312800,
            temp: 22.86,
            feels_like: 22.74,
            pressure: 1021,
            humidity: 59,
            dew_point: 13.34,
            uvi: 1.65,
            clouds: 18,
            visibility: 10000,
            wind_speed: 3.19,
            wind_deg: 298,
            wind_gust: 6.93,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750316400,
            temp: 23.82,
            feels_like: 23.67,
            pressure: 1021,
            humidity: 54,
            dew_point: 13.91,
            uvi: 3.16,
            clouds: 10,
            visibility: 10000,
            wind_speed: 3.74,
            wind_deg: 303,
            wind_gust: 5.98,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750320000,
            temp: 25.4,
            feels_like: 25.28,
            pressure: 1020,
            humidity: 49,
            dew_point: 13.82,
            uvi: 5.04,
            clouds: 10,
            visibility: 10000,
            wind_speed: 3.66,
            wind_deg: 307,
            wind_gust: 5.12,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750323600,
            temp: 26.61,
            feels_like: 26.61,
            pressure: 1020,
            humidity: 46,
            dew_point: 14.02,
            uvi: 6.87,
            clouds: 10,
            visibility: 10000,
            wind_speed: 3.87,
            wind_deg: 312,
            wind_gust: 5.03,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750327200,
            temp: 27.56,
            feels_like: 27.55,
            pressure: 1020,
            humidity: 44,
            dew_point: 14.24,
            uvi: 8.07,
            clouds: 10,
            visibility: 10000,
            wind_speed: 3.55,
            wind_deg: 317,
            wind_gust: 4.77,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750330800,
            temp: 27.91,
            feels_like: 27.94,
            pressure: 1019,
            humidity: 45,
            dew_point: 14.59,
            uvi: 6.5,
            clouds: 11,
            visibility: 10000,
            wind_speed: 3.56,
            wind_deg: 312,
            wind_gust: 4.87,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0.13,
        },
        {
            dt: 1750334400,
            temp: 26.07,
            feels_like: 26.07,
            pressure: 1020,
            humidity: 52,
            dew_point: 15.12,
            uvi: 2.42,
            clouds: 24,
            visibility: 10000,
            wind_speed: 3.11,
            wind_deg: 313,
            wind_gust: 4.36,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0.16,
        },
        {
            dt: 1750338000,
            temp: 24.96,
            feels_like: 24.97,
            pressure: 1020,
            humidity: 56,
            dew_point: 15.43,
            uvi: 2.24,
            clouds: 98,
            visibility: 10000,
            wind_speed: 2.35,
            wind_deg: 313,
            wind_gust: 4.33,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750341600,
            temp: 23.95,
            feels_like: 23.97,
            pressure: 1020,
            humidity: 60,
            dew_point: 15.38,
            uvi: 2.49,
            clouds: 100,
            visibility: 10000,
            wind_speed: 2.29,
            wind_deg: 312,
            wind_gust: 5.2,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750345200,
            temp: 24.94,
            feels_like: 24.9,
            pressure: 1019,
            humidity: 54,
            dew_point: 14.85,
            uvi: 1.1,
            clouds: 100,
            visibility: 10000,
            wind_speed: 3.3,
            wind_deg: 313,
            wind_gust: 6.06,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750348800,
            temp: 23.39,
            feels_like: 23.38,
            pressure: 1020,
            humidity: 61,
            dew_point: 15.22,
            uvi: 0.5,
            clouds: 100,
            visibility: 10000,
            wind_speed: 3.24,
            wind_deg: 342,
            wind_gust: 7.18,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.02,
        },
        {
            dt: 1750352400,
            temp: 23.81,
            feels_like: 23.79,
            pressure: 1020,
            humidity: 59,
            dew_point: 15.05,
            uvi: 0.33,
            clouds: 92,
            visibility: 10000,
            wind_speed: 4.09,
            wind_deg: 343,
            wind_gust: 7.49,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.06,
        },
        {
            dt: 1750356000,
            temp: 22.64,
            feels_like: 22.55,
            pressure: 1021,
            humidity: 61,
            dew_point: 14.51,
            uvi: 0.12,
            clouds: 93,
            visibility: 10000,
            wind_speed: 3.78,
            wind_deg: 347,
            wind_gust: 8,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04d',
                },
            ],
            pop: 0.04,
        },
        {
            dt: 1750359600,
            temp: 21.82,
            feels_like: 21.44,
            pressure: 1022,
            humidity: 53,
            dew_point: 11.57,
            uvi: 0,
            clouds: 100,
            visibility: 10000,
            wind_speed: 4.43,
            wind_deg: 354,
            wind_gust: 8.45,
            weather: [
                {
                    id: 804,
                    main: 'Clouds',
                    description: 'overcast clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750363200,
            temp: 20.05,
            feels_like: 19.44,
            pressure: 1023,
            humidity: 51,
            dew_point: 9.48,
            uvi: 0,
            clouds: 79,
            visibility: 10000,
            wind_speed: 3.42,
            wind_deg: 336,
            wind_gust: 9.96,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750366800,
            temp: 19.48,
            feels_like: 18.84,
            pressure: 1023,
            humidity: 52,
            dew_point: 9.14,
            uvi: 0,
            clouds: 74,
            visibility: 10000,
            wind_speed: 2.47,
            wind_deg: 327,
            wind_gust: 8.67,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750370400,
            temp: 19.44,
            feels_like: 18.8,
            pressure: 1024,
            humidity: 52,
            dew_point: 9.13,
            uvi: 0,
            clouds: 80,
            visibility: 10000,
            wind_speed: 2.45,
            wind_deg: 314,
            wind_gust: 6.57,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750374000,
            temp: 18.86,
            feels_like: 18.21,
            pressure: 1024,
            humidity: 54,
            dew_point: 9.3,
            uvi: 0,
            clouds: 84,
            visibility: 10000,
            wind_speed: 2.21,
            wind_deg: 306,
            wind_gust: 5.01,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750377600,
            temp: 17.37,
            feels_like: 16.76,
            pressure: 1024,
            humidity: 61,
            dew_point: 9.44,
            uvi: 0,
            clouds: 78,
            visibility: 10000,
            wind_speed: 2.23,
            wind_deg: 293,
            wind_gust: 4.84,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750381200,
            temp: 17.4,
            feels_like: 16.76,
            pressure: 1024,
            humidity: 60,
            dew_point: 9.38,
            uvi: 0,
            clouds: 74,
            visibility: 10000,
            wind_speed: 2.25,
            wind_deg: 306,
            wind_gust: 5.14,
            weather: [
                {
                    id: 803,
                    main: 'Clouds',
                    description: 'broken clouds',
                    icon: '04n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750384800,
            temp: 16.15,
            feels_like: 15.49,
            pressure: 1024,
            humidity: 64,
            dew_point: 9.15,
            uvi: 0,
            clouds: 41,
            visibility: 10000,
            wind_speed: 1.99,
            wind_deg: 322,
            wind_gust: 4.91,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03n',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750388400,
            temp: 15.04,
            feels_like: 14.35,
            pressure: 1024,
            humidity: 67,
            dew_point: 8.67,
            uvi: 0,
            clouds: 27,
            visibility: 10000,
            wind_speed: 1.77,
            wind_deg: 320,
            wind_gust: 3.16,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750392000,
            temp: 15.32,
            feels_like: 14.55,
            pressure: 1025,
            humidity: 63,
            dew_point: 8.12,
            uvi: 0.2,
            clouds: 20,
            visibility: 10000,
            wind_speed: 1.68,
            wind_deg: 319,
            wind_gust: 3.01,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750395600,
            temp: 16.63,
            feels_like: 15.78,
            pressure: 1025,
            humidity: 55,
            dew_point: 7.32,
            uvi: 0.67,
            clouds: 16,
            visibility: 10000,
            wind_speed: 1.85,
            wind_deg: 334,
            wind_gust: 3.35,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750399200,
            temp: 17.87,
            feels_like: 17.02,
            pressure: 1025,
            humidity: 50,
            dew_point: 7.14,
            uvi: 1.62,
            clouds: 14,
            visibility: 10000,
            wind_speed: 2.01,
            wind_deg: 338,
            wind_gust: 3.44,
            weather: [
                {
                    id: 801,
                    main: 'Clouds',
                    description: 'few clouds',
                    icon: '02d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750402800,
            temp: 19.21,
            feels_like: 18.39,
            pressure: 1025,
            humidity: 46,
            dew_point: 7.09,
            uvi: 3.06,
            clouds: 0,
            visibility: 10000,
            wind_speed: 2.66,
            wind_deg: 340,
            wind_gust: 4.09,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750406400,
            temp: 20.61,
            feels_like: 19.77,
            pressure: 1025,
            humidity: 40,
            dew_point: 6.43,
            uvi: 4.83,
            clouds: 0,
            visibility: 10000,
            wind_speed: 2.99,
            wind_deg: 344,
            wind_gust: 4.66,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750410000,
            temp: 21.84,
            feels_like: 21.02,
            pressure: 1025,
            humidity: 36,
            dew_point: 6.08,
            uvi: 6.55,
            clouds: 0,
            visibility: 10000,
            wind_speed: 3.43,
            wind_deg: 344,
            wind_gust: 5.02,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750413600,
            temp: 22.73,
            feels_like: 21.95,
            pressure: 1025,
            humidity: 34,
            dew_point: 6.09,
            uvi: 7.81,
            clouds: 0,
            visibility: 10000,
            wind_speed: 3.79,
            wind_deg: 342,
            wind_gust: 5.15,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750417200,
            temp: 23.61,
            feels_like: 22.86,
            pressure: 1024,
            humidity: 32,
            dew_point: 5.94,
            uvi: 8.21,
            clouds: 0,
            visibility: 10000,
            wind_speed: 3.79,
            wind_deg: 339,
            wind_gust: 5.26,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750420800,
            temp: 24.44,
            feels_like: 23.72,
            pressure: 1023,
            humidity: 30,
            dew_point: 5.67,
            uvi: 7.65,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.04,
            wind_deg: 340,
            wind_gust: 5.38,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750424400,
            temp: 24.76,
            feels_like: 24.05,
            pressure: 1023,
            humidity: 29,
            dew_point: 5.47,
            uvi: 6.33,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.23,
            wind_deg: 342,
            wind_gust: 5.55,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750428000,
            temp: 24.76,
            feels_like: 24.02,
            pressure: 1023,
            humidity: 28,
            dew_point: 5.13,
            uvi: 4.58,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.31,
            wind_deg: 343,
            wind_gust: 5.52,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750431600,
            temp: 24.48,
            feels_like: 23.71,
            pressure: 1023,
            humidity: 28,
            dew_point: 4.97,
            uvi: 2.81,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.39,
            wind_deg: 344,
            wind_gust: 5.64,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750435200,
            temp: 23.75,
            feels_like: 22.96,
            pressure: 1023,
            humidity: 30,
            dew_point: 5.27,
            uvi: 1.39,
            clouds: 0,
            visibility: 10000,
            wind_speed: 4.15,
            wind_deg: 343,
            wind_gust: 5.59,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
        {
            dt: 1750438800,
            temp: 22.91,
            feels_like: 22.14,
            pressure: 1023,
            humidity: 34,
            dew_point: 6.07,
            uvi: 0.53,
            clouds: 0,
            visibility: 10000,
            wind_speed: 3.64,
            wind_deg: 343,
            wind_gust: 5.08,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            pop: 0,
        },
    ],
    daily: [
        {
            dt: 1750240800,
            sunrise: 1750215212,
            sunset: 1750273067,
            moonrise: 1750200360,
            moonset: 1750242360,
            moon_phase: 0.75,
            summary: 'Expect a day of partly cloudy with clear spells',
            temp: {
                day: 26.46,
                min: 14.01,
                max: 28.8,
                night: 23.74,
                eve: 26.63,
                morn: 15.86,
            },
            feels_like: {
                day: 26.46,
                night: 23.74,
                eve: 26.63,
                morn: 15.62,
            },
            pressure: 1022,
            humidity: 50,
            dew_point: 12.95,
            wind_speed: 2.73,
            wind_deg: 348,
            wind_gust: 3.14,
            weather: [
                {
                    id: 802,
                    main: 'Clouds',
                    description: 'scattered clouds',
                    icon: '03d',
                },
            ],
            clouds: 41,
            pop: 0,
            uvi: 8.45,
        },
        {
            dt: 1750327200,
            sunrise: 1750301618,
            sunset: 1750359486,
            moonrise: 1750287720,
            moonset: 1750333500,
            moon_phase: 0.77,
            summary: 'Expect a day of partly cloudy with clear spells',
            temp: {
                day: 27.56,
                min: 17.99,
                max: 27.91,
                night: 19.48,
                eve: 23.39,
                morn: 18.25,
            },
            feels_like: {
                day: 27.55,
                night: 18.84,
                eve: 23.38,
                morn: 17.96,
            },
            pressure: 1020,
            humidity: 44,
            dew_point: 14.24,
            wind_speed: 4.43,
            wind_deg: 354,
            wind_gust: 9.96,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 10,
            pop: 0.16,
            uvi: 8.07,
        },
        {
            dt: 1750413600,
            sunrise: 1750388026,
            sunset: 1750445902,
            moonrise: 1750375080,
            moonset: 1750424820,
            moon_phase: 0.81,
            summary:
                'The day will start with partly cloudy through the late morning hours, transitioning to clearing',
            temp: {
                day: 22.73,
                min: 15.04,
                max: 24.76,
                night: 16.62,
                eve: 23.75,
                morn: 15.32,
            },
            feels_like: {
                day: 21.95,
                night: 15.85,
                eve: 22.96,
                morn: 14.55,
            },
            pressure: 1025,
            humidity: 34,
            dew_point: 6.09,
            wind_speed: 4.39,
            wind_deg: 344,
            wind_gust: 6.57,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 0,
            pop: 0,
            uvi: 8.21,
        },
        {
            dt: 1750500000,
            sunrise: 1750474437,
            sunset: 1750532316,
            moonrise: 1750462560,
            moonset: 1750516320,
            moon_phase: 0.85,
            summary: 'There will be partly cloudy until morning, then clearing',
            temp: {
                day: 24.16,
                min: 13.27,
                max: 26.56,
                night: 17.75,
                eve: 25.66,
                morn: 13.91,
            },
            feels_like: {
                day: 23.31,
                night: 16.81,
                eve: 24.93,
                morn: 12.98,
            },
            pressure: 1024,
            humidity: 26,
            dew_point: 3.45,
            wind_speed: 3.26,
            wind_deg: 51,
            wind_gust: 5.88,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 0,
            pop: 0,
            uvi: 7.92,
        },
        {
            dt: 1750586400,
            sunrise: 1750560850,
            sunset: 1750618727,
            moonrise: 1750550340,
            moonset: 1750608000,
            moon_phase: 0.88,
            summary: 'There will be clear sky today',
            temp: {
                day: 23.78,
                min: 14.34,
                max: 30.34,
                night: 21.28,
                eve: 30.34,
                morn: 14.34,
            },
            feels_like: {
                day: 23.02,
                night: 20.59,
                eve: 28.52,
                morn: 13.27,
            },
            pressure: 1022,
            humidity: 31,
            dew_point: 5.46,
            wind_speed: 4.19,
            wind_deg: 144,
            wind_gust: 8.56,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 0,
            pop: 0,
            uvi: 7.92,
        },
        {
            dt: 1750672800,
            sunrise: 1750647266,
            sunset: 1750705135,
            moonrise: 1750638540,
            moonset: 1750699620,
            moon_phase: 0.92,
            summary:
                'You can expect clear sky in the morning, with partly cloudy in the afternoon',
            temp: {
                day: 29.52,
                min: 16.83,
                max: 34.79,
                night: 25.68,
                eve: 34.79,
                morn: 16.83,
            },
            feels_like: {
                day: 28.14,
                night: 25.53,
                eve: 32.93,
                morn: 16,
            },
            pressure: 1015,
            humidity: 27,
            dew_point: 8.75,
            wind_speed: 3.69,
            wind_deg: 181,
            wind_gust: 8.68,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 0,
            pop: 0,
            uvi: 8,
        },
        {
            dt: 1750759200,
            sunrise: 1750733684,
            sunset: 1750791541,
            moonrise: 1750727460,
            moonset: 1750790640,
            moon_phase: 0.96,
            summary: 'Expect a day of partly cloudy with rain',
            temp: {
                day: 26.67,
                min: 21.57,
                max: 27.62,
                night: 22.56,
                eve: 27.62,
                morn: 21.84,
            },
            feels_like: {
                day: 26.96,
                night: 22.52,
                eve: 27.53,
                morn: 22.14,
            },
            pressure: 1016,
            humidity: 47,
            dew_point: 14.26,
            wind_speed: 7.33,
            wind_deg: 281,
            wind_gust: 15.42,
            weather: [
                {
                    id: 500,
                    main: 'Rain',
                    description: 'light rain',
                    icon: '10d',
                },
            ],
            clouds: 78,
            pop: 0.85,
            rain: 1.47,
            uvi: 8,
        },
        {
            dt: 1750845600,
            sunrise: 1750820105,
            sunset: 1750877944,
            moonrise: 1750817280,
            moonset: 1750880700,
            moon_phase: 0,
            summary: 'Expect a day of partly cloudy with clear spells',
            temp: {
                day: 25.83,
                min: 18.64,
                max: 30.27,
                night: 22.25,
                eve: 30.27,
                morn: 18.64,
            },
            feels_like: {
                day: 25.41,
                night: 21.99,
                eve: 28.93,
                morn: 18.13,
            },
            pressure: 1019,
            humidity: 36,
            dew_point: 9.44,
            wind_speed: 4.95,
            wind_deg: 278,
            wind_gust: 11.96,
            weather: [
                {
                    id: 800,
                    main: 'Clear',
                    description: 'clear sky',
                    icon: '01d',
                },
            ],
            clouds: 0,
            pop: 0.16,
            uvi: 8,
        },
    ],
};
