export const DEFAULT_WEATHER_ICON_ID = '800';

export const HOURLY_FORECAST_COUNT = 5;
export const DAILY_FORECAST_COUNT = 5;

export const DEFAULT_LOWER_LIMIT_TEMPERATURE = 0; // °C
export const DEFAULT_HIGHER_LIMIT_TEMPERATURE = 35; // °C
export const DEFAULT_TEMPERATURE_OFFSET = 3;
