name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REACT_APP_OPENWEATHER_APP_ID: ${{ secrets.REACT_APP_OPENWEATHER_APP_ID }}
  REACT_APP_COINSTATS_PROTFOLIO_TOKEN: ${{ secrets.REACT_APP_COINSTATS_PROTFOLIO_TOKEN }}

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - run: npm run build
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.webtip.sk
        protocol: ftp
        port: 21
        username: github_deploy.webtip.sk
        password: ${{ secrets.FTP_PASSWORD }}
        dangerous-clean-slate: true
        local-dir: ./build/